{
  "openapi": "3.0.0",
  "info": {
    "title": "iParking API",
    "version": "1.0.0",
    "contact": {
      "name": "iParking",
      "url": "localhost:3333/",
      "email": "amoslima@ufpi.edu.br"
    }
  },
  "servers": [
    {
      "url": "localhost:3333/v1",
      "description": "Local server"
    },
    {
      "url": "https://iparking-api.herokuapp.com/v1",
      "description": "Production API "
    }
  ],
  "paths": {
    "/parking": {
      "post": {
        "sumary": "Cadastro de estacionamento",
        "description": "Esta rota é responsável por cadastrar um novo estacionamento",
        "tags": ["Parking"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Parking"
              },
              "examples": {
                "Parking": {
                  "value": {
                    "image_url": "https://api.unsplash.com/photos/random",
                    "mail": "myemailexample@mail.com",
                    "phone": "999999999",
                    "name": "Le Guard",
                    "parking_spaces": 20,
                    "first_price": 5.99,
                    "price": 5,
                    "atitude": "54548965",
                    "longitude": "66515321"
                  }
                }
              }
            }
          }
        },
        "responses": {}
      }, 
      "get": {
        "sumary": "busca de estacionamento",
        "descrition": "esta rota é responsavel por buscar todos estacionamentos",
        "tags": ["Parking"],
        "requestBody":{
          "content": {
            "application/json": {
              "schema": {
                "$ref":"#/components/schemas/Parking"
              },
              "examples": {
                "Parking": {
                  "value": {                    
                  }                  
                }
              }             
            }
          }
        }
      }
      
    },
    "/parking/{id}":{
      "delete":{
        "sumary": "deletar um estacionamento",
        "descrition": "esta rota é responsavel por deletar algum estacionamentos",
        "tags": ["Parking"],
        "requestBody":{
          "content": {
            "application/json": {
              "schema": {
                "$ref":"#/components/schemas/Parking"
              },
              "examples": {
                "Parking": {
                  "value": {                    
                  }                  
                }
              }             
            }
          }
        }

      },
      "put": {
        "sumary": "busca de estacionamento",
        "descrition": "esta rota é responsavel por buscar todos estacionamentos",
        "tags": ["Parking"],
        "requestBody":{
          "content": {
            "application/json": {
              "schema": {
                "$ref":"#/components/schemas/Parking"
              },
              "examples": {
                "Parking": {
                  "value": { 
                    "value": {
                      "image_url": "https://api.unsplash.com/photos/random",
                      "mail": "myemailexample@mail.com",
                      "phone": "999999999",
                      "name": "Le Guard",
                      "parking_spaces": 20,
                      "first_price": 5.99,
                      "price": 5,
                      "atitude": "54548965",
                      "longitude": "66515321"
                    }                   
                  }                  
                }
              }             
            }
          }
        }
      }
    },
    "/ticket": {
      "post": {
        "sumary": "Cadastro de ticket",
        "description": "Esta rota é responsável por cadastrar um novo ticket",
        "tags": ["Ticket"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Ticket"
              },
              "examples": {
                "Ticket": {
                  "value": {
                    "user_id":"2d376085-81a2-42a3-80a4-ab06dcf8dbb5",
                    "parking_id": "f040d012-c308-4181-b037-e91746c1e98a"
                  }
                }
              }
            }
          }
        },
        "responses": {}
      },
      "put": {
        "sumary": "Cadastro de ticket",
        "description": "Esta rota é responsável por cadastrar um novo ticket",
        "tags": ["Ticket"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Ticket"
              },
              "examples": {
                "Ticket": {
                  "value": {
                    "user_id":"2d376085-81a2-42a3-80a4-ab06dcf8dbb5",
                    "parking_id": "f040d012-c308-4181-b037-e91746c1e98a"
                  }
                }
              }
            }
          }
        },
        "responses": {}
      },
      "get":{
        "sumary": "Cadastro de ticket",
        "description": "Esta rota é responsável por cadastrar um novo ticket",
        "tags": ["Ticket"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Ticket"
              },
              "examples": {
                "Ticket": {
                  "value": {
                    "user_id":"2d376085-81a2-42a3-80a4-ab06dcf8dbb5",
                    "parking_id": "f040d012-c308-4181-b037-e91746c1e98a"
                  }
                }
              }
            }
          }
        },
        "responses": {}
      },
      "delete":{
        "sumary": "Cadastro de ticket",
        "description": "Esta rota é responsável por cadastrar um novo ticket",
        "tags": ["Ticket"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Ticket"
              },
              "examples": {
                "Ticket": {
                  "value": {
                    "user_id":"2d376085-81a2-42a3-80a4-ab06dcf8dbb5",
                    "parking_id": "f040d012-c308-4181-b037-e91746c1e98a"
                  }
                }
              }
            }
          }
        },
        "responses": {}
      }
    },
    "/users": {
      "post": {
        "sumary": "Cadastro de usuario",
        "description": "Esta rota é responsável por cadastrar um novo usuario",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "User": {
                  "value": {                    
                    "mail": "myemailexample@mail.com",
                    "name": "claudio jaime",
                    "password": "66515321",
                    "confirmePassword": "66515321"
                  }
                }
              }
            }
          }
        },
        "responses": {}
      },
      "put": {
        "sumary": "atualizacao de usuario",
        "description": "Esta rota é responsável por atualizar um novo usuario",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "User": {
                  "value": {                    
                    "mail": "myemailexample@mail.com",
                    "name": "claudio jaime",
                    "password": "66515321"
                  }
                }
              }
            }
          }
        },
        "responses": {}
      }

    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {         
          "mail": {
            "type": "string"
          },     
          "name": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "Parking": {
            "type": "object"
          }
        }
      },
      "Parking": {
        "type": "object",
        "properties": {
          "image_url": {
            "type": "string"
          },
          "mail": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "parking_spaces" : {
            "type": "number"
          },
          "first_price": {
            "type": "number"
          },
          "price": {
            "type": "number"
          },
          "latitude": {
            "type": "string"
          },
          "longitude": {
            "type": "string"
          }
        }
      },
      "Ticket": {
        "type": "object",
        "properties": {
          "user_id": {
            "type": "string"
          },
          "parking": {
            "type": "object"
          },
          "parking_id": {
            "type": "string"
          },
          "time_checkin": {
            "type": "datetime"
          },
          "time_checkout" : {
            "type": "datatime"
          },
          "price": {
            "type": "number"
          },
          "status": {
            "type": "string"
          }
        }
      }
    }
  }
}
